package cn.myproject.wstl.common;


import cn.myproject.wstl.array.LongArray;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IMCWebService", targetNamespace = "http://common.hd.slsd.nari.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IMCWebService {

	/**
	 * 
	 * @param arg0
	 * @return returns com.nari.slsd.hd.common.CharDataWSArray
	 */
	@WebMethod
	@WebResult(partName = "return")
	public CharDataWSArray getNCRealData(
            @WebParam(name = "arg0", partName = "arg0") LongArray arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns com.nari.slsd.hd.common.CharDataWSArray
	 */
	@WebMethod
	@WebResult(partName = "return")
	public CharDataWSArray getWDSData(
            @WebParam(name = "arg0", partName = "arg0") WebFetchParam arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1,
            @WebParam(name = "arg2", partName = "arg2") String arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(partName = "return")
	public boolean validUser(
            @WebParam(name = "arg0", partName = "arg0") String arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @param arg7
	 * @param arg8
	 * @param arg9
	 * @return returns com.nari.slsd.hd.common.CharDataWSArray
	 */
	@WebMethod
	@WebResult(partName = "return")
	public CharDataWSArray getWDSTimeSerialData(
            @WebParam(name = "arg0", partName = "arg0") LongArray arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1,
            @WebParam(name = "arg2", partName = "arg2") String arg2,
            @WebParam(name = "arg3", partName = "arg3") String arg3,
            @WebParam(name = "arg4", partName = "arg4") String arg4,
            @WebParam(name = "arg5", partName = "arg5") String arg5,
            @WebParam(name = "arg6", partName = "arg6") String arg6,
            @WebParam(name = "arg7", partName = "arg7") String arg7,
            @WebParam(name = "arg8", partName = "arg8") String arg8,
            @WebParam(name = "arg9", partName = "arg9") String arg9);

	/**
	 * 
	 * @param arg0
	 * @return returns com.nari.slsd.hd.common.WdsHydroCurvedArray
	 */
	@WebMethod
	@WebResult(partName = "return")
	public WdsHydroCurvedArray getWdsHydroCurveds(
            @WebParam(name = "arg0", partName = "arg0") long arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns com.nari.slsd.hd.common.CharDataWSArray
	 */
	@WebMethod
	@WebResult(partName = "return")
	public CharDataWSArray getWDSRealData(
            @WebParam(name = "arg0", partName = "arg0") LongArray arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1,
            @WebParam(name = "arg2", partName = "arg2") String arg2);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @param arg7
	 * @return returns com.nari.slsd.hd.common.CharDataWSArray
	 */
	@WebMethod
	@WebResult(partName = "return")
	public CharDataWSArray getNCTimeSerialData(
            @WebParam(name = "arg0", partName = "arg0") LongArray arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1,
            @WebParam(name = "arg2", partName = "arg2") String arg2,
            @WebParam(name = "arg3", partName = "arg3") String arg3,
            @WebParam(name = "arg4", partName = "arg4") String arg4,
            @WebParam(name = "arg5", partName = "arg5") String arg5,
            @WebParam(name = "arg6", partName = "arg6") String arg6,
            @WebParam(name = "arg7", partName = "arg7") String arg7);

}
